services:
  ml-detector-app:
    container_name: pfnd-ml-detector-app
    build:
      context: ./pfnd-ml-detector-app
      dockerfile: Dockerfile
    environment:
        ENV: "dev"
    ports:
      - "8000:8000"
    volumes:
      - pfnd2025_data:/ml-detector-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pfnd2025_data: