###
POST localhost:8080/app/evaluate
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyX3Rlc3QiLCJlbWFpbEFkZHJlc3MiOiJ1c2VyX3Rlc3RAdGVzdC5tYWlsIiwidXNlcklkIjoxLCJpYXQiOjE3NTAwOTEwMTEsImV4cCI6MTIwMDE3NTAwOTEwMTF9.9jv3d2Pe51W9tLavetIoU_UnjP9xW9lKliov3YY7VnU
Content-Type: application/json

{
  "text": "Text"
}
###
GET localhost:8080/app/status/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyX3Rlc3QiLCJlbWFpbEFkZHJlc3MiOiJ1c2VyX3Rlc3RAdGVzdC5tYWlsIiwidXNlcklkIjoxLCJpYXQiOjE3NTAwOTEwMTEsImV4cCI6MTIwMDE3NTAwOTEwMTF9.9jv3d2Pe51W9tLavetIoU_UnjP9xW9lKliov3YY7VnU
Content-Type: application/json

###
GET localhost:8080/app/result/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyX3Rlc3QiLCJlbWFpbEFkZHJlc3MiOiJ1c2VyX3Rlc3RAdGVzdC5tYWlsIiwidXNlcklkIjoxLCJpYXQiOjE3NTAwOTEwMTEsImV4cCI6MTIwMDE3NTAwOTEwMTF9.9jv3d2Pe51W9tLavetIoU_UnjP9xW9lKliov3YY7VnU
Content-Type: application/json

###

GET localhost:8080/app/history
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyX3Rlc3QiLCJlbWFpbEFkZHJlc3MiOiJ1c2VyX3Rlc3RAdGVzdC5tYWlsIiwidXNlcklkIjoxLCJpYXQiOjE3NTAwOTEwMTEsImV4cCI6MTIwMDE3NTAwOTEwMTF9.9jv3d2Pe51W9tLavetIoU_UnjP9xW9lKliov3YY7VnU
Content-Type: application/json
