POST http://localhost:8080/app/user/register
Content-Type: application/json

{
  "email": "242544",
  "password": "test"
}

###
GET http://localhost:8080/app/user

###

POST http://localhost:8080/app/user/login
Content-Type: application/json

{
  "usernameOrEmail": "242544",
  "password": "test"
}